01 button
js-tasks-ru/htmlcss-20210916_gamesdi pull request #3
Opened 2021-09-22 19:37 UTC by Krimson-Sun

2021-09-22 19:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-26 10:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-28 19:15 UTC, GSemikozov requested changes

2021-09-28 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
здесь речь о модификаторе (модифицируем кнопку), не об отдельном элементе, поэтому - модификаторы пишем через одно нижнее подчеркивание вместо двух. И ниже то же самое

2021-09-28 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-style: none;
чтобы не сбрасывать стили бордера, лучше на уровне button задать border: none + box-sizing: border-box

2021-09-28 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: white;
так цвет есть в переменных)

2021-09-28 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
еще принято добавлять pointer-events: none (чтобы пользователь не мог взаимодействовать с такими элементами)

2021-09-28 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +:disabled {
тут наверно должен быть класс .button. :)

2021-09-28 19:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: #2342C0;
тут и ниже - цвета надо забрать из переменных (если таковых нет, то создать)

2021-09-29 10:01 UTC, closed without merging